# .xinitrc - curated by budRich

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

udiskie &
# sudo systemctl e netctl-auto@wlo1-Tele2Internet-e197.service

xset -b b off

xrandr --output LVDS1 --auto --primary

hsetroot -tile /home/bud/etc/bitmap-walls/patterns-png/line_diag3_2.png \
  -tint "$(xrdb -query | awk '/colors.act1/ {print $2}')"

setxkbmap -layout seba -option lv3:ralt_switch -option 'caps:ctrl_modifier'
xcape -e 'Caps_Lock=Escape'
numlockx off > /dev/null 2>&1
# xinput set-prop 17 139 0

urxvtd -q -o -f
# dropbox start &
compton -b > /dev/null 2>&1
thunar --daemon &
dunst > /dev/null 2>&1 &

pidof qbittorrent && killall qbittorrent

flashfocus -s -t 175 -o 0.92 -e 1 > /dev/null 2>&1 &
sxhkd > /dev/null 2>&1 &

xbanish &

export QT_QPA_PLATFORMTHEME=qt5ct
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

. $HOME/.i3env
exec i3

# syntax:ssHash
